### PR TITLE
Display Events

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
Adds Cards to display the incoming events

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍

**Comment by Cahllagerfeld** [comment]
It still has two small hiccups 
1. The newest event gets displayed at the bottom, and not at the top.
2. The list of events isn't sticky. Once the list exceeds the viewport the entire page + map scrolls, and not just the column

In terms of DX we should also look into having some mock data, because to develop this I had to trigger the sockets manually

**Comment by eddiejaoude** [comment]
We can continue to improve/tweak it, hopefully the community will help too.

> In terms of DX we should also look into having some mock data, because to develop this I had to trigger the sockets manually

Yes great idea 👍 

Let me know if you would like to pair together on it

**Comment by Cahllagerfeld** [comment]
test event

**Comment by Cahllagerfeld** [comment]
test event

**Pull request merged**
