### PR TITLE
New Card Style

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
Rough suggestion for updating the event cards

- added a new off-white for the background
- changed tailwind config to pick this new value up
- adjusted the card

grafik

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks Cahl! Could you add a screenshot please?

Do you see this PR being merged, or because it is a draft more work is done first?

**Comment by Cahllagerfeld** [comment]
It's marked as draft, because it's more like a suggestion, we can definitely merge it though 👍

**Comment by Cahllagerfeld** [comment]
Test comment for triggering an event

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍

**Review by amandamartin-dev — APPROVED** [review]
looks good to me! Clean UI update. Code is fine.

**Comment by Cahllagerfeld** [comment]
Awesome, thank you all!

**Pull request merged**
