### PR TITLE
Migrate to Vite

### LINKED ISSUE #71: [OTHER] Improvement add eslint
### What would you like to share?

add linter to enforce formatting

### Additional information

_No response_

### LINKED ISSUE #72: [FEATURE] Migrate Webpack to Vite
### Description

The app was created with `create-react-app`. We want to move to Vite, as it's more state-of-the-art than using Webpack

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #72 
closes #71

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
I have an open ticket for eslint, but if it makes sense to just take care of it all in one go you can close that ticket as completed when this is done. wdyt?

**Review by amandamartin-dev — COMMENTED** [review]
LGTM but I think there are going to be some doc updates from this change if you wanna check the readme?
I noticed npm run start changed to run dev and maybe some links to info about Vite in general?  Not sure what else is needed.

**Review by dan-mba — CHANGES_REQUESTED** [review]
In order for `npm run dev` to serve on port 3000, you need to add the following to the vite.config.js
```
server: {
    port: 3000
  },
```

for `npm run serve` you use `vite preview --port 3000`

**Review by Cahllagerfeld — COMMENTED** [review]
I didn't adjust the port, I'd like to keep it as vanilla as possible

**Review by amandamartin-dev — APPROVED** [review]

**Comment by Cahllagerfeld** [comment]
Thanks for the collaboration 🙏

**Pull request merged**
