### PR TITLE
change favicon and meta discription

### PR DESCRIPTION
**Pull request by E-fais**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieHubLive/pull/49"></a>

### CODE REVIEW

**Review by eddiejaoude — COMMENTED** [review]
Looks good 👍 but please only commit files you changed.

If you didn't make changes to `package.json`, then the lock file should not be committed.

**Comment by E-fais** [comment]
Thank you fir reviewing 
Do i have to commit again only with changed files?

**Comment by eddiejaoude** [comment]
You can revert the changes to the file and do another commit+push to your branch and the PR will updated, but if easier for you can close the PR and make a new one - up to you 🤓

**Comment by E-fais** [comment]
I will create a new PR

**Pull request closed without merging**
