### PR TITLE
About button Stacking on mobile

### LINKED ISSUE #102: About Stacking on Mobile
### Description

The about button stacks into the event cards and the modal has not been configured for mobile use.  

Related to #101 

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sudhanshutech**
Closes #102 

## Fixes Issue
#102 

## Changes proposed

1. Dialogue box is centered and closing the dialogue box bug is resolved which was not possible earlier
image
2. About button was stacked under event cards, its being resolved and given a margin-top to 10px to cards so that button and cards could be distinguished
image

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
This may have been my miscommunication, but the about button shouldn't be where the cards are at all.  It is meant to be in the navigation at the top so I would expect 1 of 2 possibilites

Option 1: on Mobile the About is in a hamburger menu
Option 2: On Mobile the about button remains in the navigation pulled right and does not stack down (sized appropriately for mobile)

Would either of those be possible?  I'm thinking Option 2 is best because it is the only nav item so a hamburger menu is not needed

**Comment by sudhanshutech** [comment]
Oh okay. Yes, option 2 is the best option. I am gonna do it accordingly

**Comment by sudhanshutech** [comment]
@amandamartin-dev are you suggesting something like this
image

**Comment by amandamartin-dev** [comment]
> @amandamartin-dev are you suggesting something like this

Yes exactly.  The about button should stay within the nav but move to the viewable space as the viewport is resized (as opposed to stacking as it was doing before)

**Comment by amandamartin-dev** [comment]
Sorry, here is a visual. We want the nav items to stay on the same level no matter the screen size (instead of stacking as they do now)
aboutmove

**Comment by sudhanshutech** [comment]
> Sorry, here is a visual. We want the nav items to stay on the same level no matter the screen size (instead of stacking as they do now) aboutmove

Now I think this is in right place
image

**Comment by amandamartin-dev** [comment]
okay cool! So you are ready for review or still working a bit?

**Comment by sudhanshutech** [comment]
> okay cool! So you are ready for review or still working a bit?

Ya, I am ready for review. I am doing commit soon

**Comment by amandamartin-dev** [comment]
Looks like a good start! Thanks for working that out.  I'm convinced there is some unused css in all this nav code we can clean up at some point (not pressing) so I'll make a little ticket for that. Thank you so much for your contribution

**Pull request merged**
