### PR TITLE
Overflow of the body and event-card container removed

### LINKED ISSUE #79: vertical overflow, there's a scrollbar on screen
### Description

I'm not sure if it's meant to have a scrollbar, it it's intentional, feel free to close the issue
I think it shouldn't as the map can zoom in and zoom out and the location sidebar can have a separate vertical scroll

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by joshi-omkar**
## Fixes Issue

Closes #79 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
image

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
Hi @joshi-omkar did you mean to close this PR or should I review it?

**Comment by joshi-omkar** [comment]
I want to close this, there are some changes, will do it by tomorrow.

**Comment by amandamartin-dev** [comment]
Great! No rush just wanted to check it wasn't a mistake

**Review by Aadarsh805 — COMMENTED** [review]
no this is very wrong, you don't make changes to the HTML file like that
also making overflow hidden will only hide the overflowing stuff, we need that on screen

**Comment by amandamartin-dev** [comment]
Hi @Aadarsh805 this pull request is closed and not yet ready to be reviewed. Also please remember to be kind when offering feedback to others and advise on best practices in a constructive way for all. Appreciate your time but let's wait until joshi is done working.

**Pull request closed without merging**
