### PR TITLE
[UI] Responsiveness of UI 

### LINKED ISSUE #88: UI is not responsive
### Description

UI is not responsive, the event-card and About is not responsive.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sudhanshutech**
#88 

## Fixes Issue

Closes #88 

## Changes proposed

Changes are done in the (event-card.jsx) and (tailwind config js) file to make the UI responsive.
In the tailwind config file custom screen config was added for screens under 895 px the div will be flex-column.
And according to config, classes added to the event card file 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

Changes are made according to style or order of project no extra thing are added✨

### CODE REVIEW

**Review by amandamartin-dev — COMMENTED** [review]
This looks great so far!! There is one more UI element affected in the responsiveness.  Notice the "About" button that opens the modal gets stacked under the cards.  Also when the modal is open, the ability to close it becomes lost and the modal is not centered.  I think those are the last 2 items to tackle in this issue.

**Comment by amandamartin-dev** [comment]
Here's the modal issue screenshot for reference
modal

**Comment by sudhanshutech** [comment]
ok I am on it

**Comment by sudhanshutech** [comment]
for this issue, I have to make another PR. So can this PR be merged

**Pull request merged**
